const BLOCK_SIZE = 64;
const PLAINTEXT_LENGTH_MULTIPLICITY = 8;
const HEX_LENGTH_MULTIPLICITY = 16;
const SMALL_BLOCK_SIZE = 6;
const ROUNDS_NUMBER = 16;
const BITS_IN_SYMBOL = 8;

module.exports = {
    BLOCK_SIZE,
    HEX_LENGTH_MULTIPLICITY,
    PLAINTEXT_LENGTH_MULTIPLICITY,
    SMALL_BLOCK_SIZE,
    ROUNDS_NUMBER,
    BITS_IN_SYMBOL
}